config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root to: "pages#home"
  devise_for :users, :controllers => {:registrations => "registrations"}

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "patients/buscar_px", to: "patients#buscar_px", as: :buscar
  resources :doctors
  resources :patients do
    resources :consultations, only: [:new, :create, :edit, :update]
    resources :diagnoses, only: [:new, :create]
  end
  resources :blogs
  resources :consultations, except: %i[new create]
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  validate :image_validation
  validates :title, length: { in: 12..40 }
  validates :comment, length: { in: 100..250 }

  include PgSearch::Model
  pg_search_scope :search_blog,
    against: [ :title, :comment ],
    using: {
      tsearch: { prefix: true }
    }

  def image_validation
    unless Rails.env.development?
      self.photo.attached?
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_blog, only: %i[show edit update destroy]

  def index
    @blogs = Blog.all

    if params[:query].present?
      @blogs = Blog.search_blog(params[:query])
      unless @blogs.present?
        @blogs = Blog.all       
      end
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user = current_user
    if @blog.save
      redirect_to blogs_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: 'Blog actualizado exitosamente.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, status: :see_other, notice: 'Blog eliminado exitosamente.'
  end

  private

  def blog_params
    params.require(:blog).permit(:comment, :title, :photo)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/views/blogs/edit.html.erb
<div class="actualizacion-blog-form">
  <h2>Actualizacion de Información</h2>
  <hr style="border-top: 1px solid #ccc;">
  <%= simple_form_for(@blog) do |f| %>
  <%= f.input :title, class:"title"%>
  <%= f.input :comment, as: :text, class:"comment"%>
  <%= f.input :photo, as: :file, class:"photo"%>
  <%= f.submit "Guardar", class:"boton"%>
  <%= cl_image_tag @blog.photo.key, width: 300, height: 200, style: "border-radius: 10px;" if @blog.photo.attached? %>

  <% end %>
</div>

app/views/blogs/index.html.erb
<%# buscardor %>
<%= form_with url: blogs_path(), method: :get , id:"buscador"  do %>
      <%= text_field_tag :query,
            params[:query],
            class: "searchTerm",
            placeholder: "Realiza tu busqueda..."
      %>
<%end%>
<%# buscardor %>

<div class="title-blog">
  <%= link_to "Crear Blog", new_blog_path, class: "btn mb-3" %>
</div>

<div class="blog-container tm-row pb-5">
  <div class="row">
    <% @blogs.each do |blog| %>
      <div class="col-12 col-md-4 mb-3">
        <div class="card blogs-border">
          <div class="card-body">
            <div class="tm-post-link-inner">
              <% if blog.photo.present? %>
                <%= cl_image_tag blog.photo.key, alt: blog.title, class: "img-blogs" if blog.photo.present? %>
              <% else %>
                <%= image_tag "blogs/Blog.jpg", alt: "Imagen por defecto", class: "img-blogs" %>
              <% end %>
            </div>
            <div class="d-flex aligns-items-center">
            <h5 class="mb-0 tm-color-primary tm-post-title"><%= blog.title %></h5>
            </div>
            <p class=coment><%= blog.comment %></p>
            <%= link_to "Ver", blog_path(blog), class: "btn mb-3" %>

            <div class="d-flex align-items-center justify-content-between">
            <div class="link_to">
              <%= cl_image_tag blog.user.photo.key, class: "avatar rounded-circle" , id: "navbarDropdown"%>
            <%= blog.user.first_name %> <%= blog.user.last_name %></span>
            </div>
            <div class="link_to">
            <% if current_user == blog.user %>
              <%= link_to edit_blog_path(blog) do %>
                <i class="fa-solid fa-pencil text-warning ms-3"></i>
            <%end%>
            <%= link_to blog_path(blog), data: { turbo_method: :delete, turbo_confirm: '❌ ¿Estás seguro de que deseas eliminar este blog? ❌' } do %>
                <i class="fa-solid fa-trash text-danger ms-3"></i>
            <%end%>
            <%end%></div>
            </div>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="actualizacion-blog-form">
  <h2>Crear Blog</h2>
 <hr style="border-top: 1px solid #ccc;">
  <%= simple_form_for(@blog) do |f| %>
  <%= f.input :title, class:"title"%>
  <%= f.input :comment, as: :text,  class:"comment" %>
  <%= f.input :photo, as: :file, class: "photo", required: true %>
  <%= f.submit "Guardar", class:"boton" %>
<% end %>
</div>

app/views/blogs/show.html.erb
<div class="container vh-100 d-flex">
  <div class="row justify-content-center align-items-center">
    <div class="col-md-8 blog-card-container">
      <div class="blogg-border mb-3">
        <div class="card-body d-flex flex-row">
          <div class="me-3">
            <% if @blog.photo.present? %>
              <%= cl_image_tag @blog.photo.key, alt: @blog.title, class: "image" %>
            <% else %>
              <%= image_tag "blogs/Blog.jpg", alt: "Imagen por defecto", class: "img-fluid mb-3" %>
            <% end %>
          </div>
          <div>
            <h2 class="card-title mb-3"><%= @blog.title %></h2>
            <p class="texto-cardd comentario"><%= @blog.comment %></p>
            <a href="javascript:history.back()" class="btn">Volver</a>
          </div>
        </div>
      </div>
    </div>
    <%# perfil-user %>

    <%# perfil-user %>
    <div class="col-4 d-flex justify-content-center">
      <div class="col-md-4 user-details-container card">
        <div class="card-body tarjeta-perfil">
          <div class="d-flex text-black">
            <div class="flex-shrink-0">
              <%= cl_image_tag @blog.user.photo.key, alt: "Imagen de perfil", class: "imagen-cuadrada" %>
            </div>
            <div class="flex-grow-1 ms-3">
              <h5 class="mb-1"><%= @blog.user.first_name %> <%= @blog.user.last_name %></h5>
              <p><%= @blog.user.email %></p>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>