config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root to: "pages#home"
  devise_for :users, :controllers => {:registrations => "registrations"}

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "patients/buscar_px", to: "patients#buscar_px", as: :buscar
  resources :doctors
  resources :patients do
    resources :consultations, only: [:new, :create, :edit, :update]
    resources :diagnoses, only: [:new, :create]
  end
  resources :blogs
  resources :consultations, except: %i[new create]
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor

  validates :diagnostic, presence: true
end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController
  def index
  end

  def show
    @consultation = Consultation.find(params[:id])
  end

  def edit
    @consultation = Consultation.find(params[:id])
    @patient = @consultation.patient
  end

  def new
    @consultation = Consultation.new
  end

  


  def create
    #Se busca el paciente
    @patient = Patient.find(params[:patient_id])
    @doctor = current_user.doctor
    @consultation = Consultation.new(consultation_params)
    @consultation.patient_id = @patient.id
    @consultation.doctor_id = @doctor.id
    if @consultation.save!
      redirect_to patient_path(@patient)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @consultation = Consultation.find(params[:id])

    if @consultation.update(consultation_params)
      redirect_to patient_path(@consultation.patient), notice: "Consulta actualizada correctamente"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def consultation_params
    params.require(:consultation).permit(:diagnostic)
  end
end

app/views/consultations/create.html.erb
<h1>Consultations#create</h1>
<p>Find me in app/views/consultations/create.html.erb</p>

app/views/consultations/edit.html.erb
<div class="d-flex justify-content-center align-items-center">
  <div class="card card_profile">
    <%= simple_form_for @consultation, url: patient_consultation_path(patient_id: @patient.id, id: @consultation.id) do |f| %>
      <div tabindex="-1">
        <h1>Diagnóstico</h1>
        <%= f.text_area :diagnostic, class: "form-control", placeholder: "Ingrese el diagnóstico aquí" %>
      </div>
      <%= f.button :submit, "Crear consulta", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/consultations/index.html.erb
<h1>Consultations#index</h1>
<p>Find me in app/views/consultations/index.html.erb</p>

app/views/consultations/new.html.erb
  <div class="container d-flex justify-content-center vh-100 registro mt-3">
    <div class="card card_profile">
      <%= simple_form_for @consultation, url: patient_consultations_path, html: { class: "custom-form" } do |f| %>
        <div tabindex="-1">
          <h1 class="mb-3">Diagnóstico</h1>
          <%= f.text_area :diagnostic, class: "form-control-area", placeholder: "Ingrese el diagnóstico aquí", input_html: { style: "height: 300px;" } %>
        </div>
        <%= f.button :submit, "Crear consulta", class: "btn" %>
      <% end %>
    </div>
  </div>

app/views/consultations/show.html.erb
<h1>Consultations#show</h1>
<p>Find me in app/views/consultations/show.html.erb</p>

app/views/consultations/update.html.erb
<h1>Consultations#update</h1>
<p>Find me in app/views/consultations/update.html.erb</p>