config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  root to: "pages#home"
  devise_for :users, :controllers => {:registrations => "registrations"}

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "patients/buscar_px", to: "patients#buscar_px", as: :buscar
  resources :doctors
  resources :patients do
    resources :consultations, only: [:new, :create, :edit, :update]
    resources :diagnoses, only: [:new, :create]
  end
  resources :blogs
  resources :consultations, except: %i[new create]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer mt-5">
  <div class="container-fluid">
    <div class="d-flex footer-images justify-content-around align-items-center">
      <%= image_tag "aliados/fenix-salud-san-bernardino-caracas.png"%>
      <%= image_tag "aliados/sanatrix.png"%>
      <div style="text-align: center">
         <ul class="social-media">
          <li>______________</li>
          <li><a href="https://www.facebook.com/ejemplo" target="_blank"><i class="fa-brands fa-facebook-f"></i></a></li>
          <li><a href="https://www.twitter.com/ejemplo" target="_blank"><i class="fa-brands fa-x-twitter"></i></a></li>
          <li><a href="https://www.instagram.com/ejemplo" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
          <li>______________</li>
        </ul>
        <p class="m-0">
          <a href="mailto:info@ejemplo.com">selfcare.atencion@gmail.com</a><br>
          0212-572.18.30
        </p>
        <p class="m-0">&copy; 2024. Todos los derechos reservados.</p>
      </div>
      <%= image_tag "aliados/la-arboleda.png"%>
      <%= image_tag "aliados/SANTIAGO DE LEON-BLANCO-1.png"%>
    </div>
  </div>

<style>
.footer-images > img {
  /* width: 100px; */
  height: 100px;
}

</style>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon z-index">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "selfcare.png", class: "imgnavbar"  %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? && current_user.role == false  %>
          <li class="nav-item active">
            <%= link_to "Inicio",  root_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Blogs",  blogs_path , class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Doctores",  doctors_path , class: "nav-link text-white" %>
          </li>
        <% elsif user_signed_in? && current_user.role == true  %>
          <li class="nav-item active">
            <%= link_to "Inicio",  root_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Blogs",  blogs_path , class: "nav-link text-white" %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to "Iniciar sesión",  new_user_session_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Inicio",  root_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Blogs",  blogs_path , class: "nav-link text-white" %>
          </li>
        <%end  %>
        <!--!!!!!!!!!!!!!!!¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡-->
        <!--VISUALIZAR EL ESTILO DE ESTO Dropdown PORQUE ESTA FEO-->
        <!--!!!!!!!!!!!!!!!¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡¡-->
        <% if user_signed_in? && current_user.role == false  %>
          <li class="nav-item dropdown" style="margin:10px;">
            <%= cl_image_tag current_user.photo.key, class: "avatar rounded-circle" , id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false if current_user.photo.attached? %>
            <div class="dropdown-menu dropdown-menu-end bg-dark" aria-labelledby="navbarDropdown">
              <%= link_to "Mi perfil", patient_path(current_user.patient), class: "dropdown-item text-light" %>
              <%= link_to "Editar perfil", edit_user_registration_path, class: "dropdown-item text-light" %>
              <%= link_to "Cerrar sesión", destroy_user_session_path, class: "dropdown-item text-light", data: {turbo_method: :delete} %>
            </div>
          </li>
          <% elsif user_signed_in? && current_user.role == true %>
            <li class="nav-item dropdown" style="margin:10px;">
              <%= cl_image_tag current_user.photo.key, class: "avatar rounded-circle" , id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false if current_user.photo.attached? %>
              <div class="dropdown-menu dropdown-menu-end bg-dark" aria-labelledby="navbarDropdown">
              <% unless current_user.doctor.nil? %>
                <%= link_to "Mi perfil", doctor_path(current_user&.doctor), class: "dropdown-item text-light" %>
              <% end %>
                <%= link_to "Editar perfil", edit_user_registration_path, class: "dropdown-item text-light" %>
                <%= link_to "Cerrar sesión", destroy_user_session_path, class: "dropdown-item text-light", data: {turbo_method: :delete} %>
              </div>
            </li>
          <% end %>

      </ul>
    </div>
    </div>
  </div>
</div>